# Generated by Django 6.0.3 on 2026-04-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='editions/portraits/')),
            ],
        ),
    ]
